name: Backup Snipaste Versions

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行
  workflow_dispatch:  # 允许手动触发

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies  # 新增依赖安装步骤
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests  # 安装需要的库

      - name: Run backup script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python backup_snipaste.py

      - name: Commit version record
        if: success()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add versions.json
          git commit -m "Update version record" || echo "No changes to commit"
          git push
    
