name: Snipaste Auto Release

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:  # 允许手动触发

# 增加权限配置，确保有创建Release的权限
permissions:
  contents: write  # 授予内容写入权限，用于创建Release和上传文件

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Get latest release version
        id: get_latest_release
        run: |
          response=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          if echo "$response" | jq -e '.tag_name' > /dev/null; then
            LATEST_RELEASE=$(echo "$response" | jq -r '.tag_name')
          else
            LATEST_RELEASE="0.0"
          fi
          echo "Latest release: $LATEST_RELEASE"
          echo "latest_release=$LATEST_RELEASE" >> $GITHUB_OUTPUT

      - name: Check for new version and download files
        id: check_version
        run: |
          declare -A urls=(
            ["win-x64"]="https://dl.snipaste.com/win-x64"
            ["win-x86"]="https://dl.snipaste.com/win-x86"
            ["mac"]="https://dl.snipaste.com/mac"
            ["linux"]="https://dl.snipaste.com/linux"
          )
          
          mkdir -p snipaste_files
          > versions.txt
          > filenames.txt
          
          for platform in "${!urls[@]}"; do
            echo "Downloading $platform..."
            final_url=$(curl -sIL -o /dev/null -w "%{url_effective}" "${urls[$platform]}")
            filename=$(basename "$final_url")
            # 下载文件并验证是否成功
            if ! curl -L -o "snipaste_files/$filename" "${urls[$platform]}"; then
              echo "Error: 下载 $platform 失败"
              exit 1
            fi
            # 检查文件是否存在且非空
            if [ ! -s "snipaste_files/$filename" ]; then
              echo "Error: 文件 snipaste_files/$filename 不存在或为空"
              exit 1
            fi
            
            echo "Downloaded file: $filename"
            
            version=$(echo "$filename" | sed -E 's/^Snipaste-([0-9]+\.[0-9]+(\.[0-9]+)?).*$/\1/')
            if ! echo "$version" | grep -qE '^[0-9]+\.[0-9]+(\.[0-9]+)?$'; then
              echo "Error: 无法从文件名 $filename 中提取有效版本号"
              exit 1
            fi
            
            echo "Extracted version for $platform: $version"
            echo "${platform}_version=$version" >> versions.txt
            echo "${platform}_filename=$filename" >> filenames.txt
          done
          
          # 调试：确认文件列表
          echo "===== 下载的文件列表 ====="
          ls -l snipaste_files/
          echo "=========================="
          
          version_list=$(awk -F'=' '/_version/ {print $2}' versions.txt | sort -u)
          version_count=$(echo "$version_list" | wc -l | tr -d '[:space:]')
          
          if [ "$version_count" -ne 1 ]; then
            echo "Error: 各平台版本号不一致！"
            echo "检测到的版本号: $version_list"
            exit 1
          fi
          
          NEW_VERSION=$(echo "$version_list" | head -n 1 | tr -d '[:space:]')
          if [ -z "$NEW_VERSION" ]; then
            echo "Error: 未能提取有效的新版本号"
            exit 1
          fi
          
          echo "Detected version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # 生成文件路径列表，确保每个路径正确
          files_to_upload=$(awk -F'=' '/_filename/ {print "snipaste_files/" $2}' filenames.txt | tr '\n' ' ')
          echo "files=$files_to_upload" >> $GITHUB_OUTPUT
          # 调试：打印要上传的文件路径
          echo "===== 要上传的文件路径 ====="
          echo "$files_to_upload"
          echo "=========================="

      - name: Create release if new version
        if: steps.check_version.outputs.new_version != steps.get_latest_release.outputs.latest_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.check_version.outputs.new_version }}
          name: Snipaste ${{ steps.check_version.outputs.new_version }}
          body: |
            Auto-released version ${{ steps.check_version.outputs.new_version }}
            Contains builds for:
            - Windows x64
            - Windows x86
            - macOS
            - Linux
          files: ${{ steps.check_version.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
