name: 备份 Snipaste 版本

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行备份脚本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python backup_snipaste.py

      - name: 保存版本记录
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "更新版本记录"
          file_pattern: "versions.json"
